name: Check important files and deploy to pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  check_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check index.html
        run: |
          if [[ ! -f "index.html" ]]; then
            echo "index.html does not exist."
            exit
          fi
      - name: Check script.js
        run: |
          if [[ ! -f "./js/script.js" ]]; then
            echo "script.js does not exist."
            exit
          fi
      - name: Check style.css
        run: |
          if [[ ! -f "./css/style.css" ]]; then
            echo "style.css does not exist."
            exit
          fi
      - name: Check profile.png
        run: |
          if [[ ! -f "./images/profile.png" ]]; then
            echo "profile.png does not exist."
            exit
          fi
      - name: Check complete
        run: |
          echo "Check complete! Important files exist!"
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
